version: "3"
networks:
  amanynetwork:

services:
  amany_server:
    build: .
    container_name: "amany_server"
    ports:
      - "80:80"
    volumes:
      - "./application:/var/www/html"
    working_dir: "/var/www/html"
    networks:
      - "amanynetwork"
